### ISSUE TITLE
Pin Displays

### ISSUE THREAD

**Issue by Aetheris743** [BSU-SUITS-Team/CHUCK#105]
- [ ] Pins should be displayable in the LMCC #103 
- [ ] Pins should be displayable in the HMD #104 
- [ ] There should be a pin backend #101 
- [ ] Pins should have visible lables #106
